# Generated by Django 4.1.7 on 2023-03-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework62', '0002_alter_issue_description_alter_issue_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
